### ISSUE TITLE
Move docs into the separate wiki?

### ISSUE THREAD

**Issue by j127** [codeselfstudy/codeselfstudy#19]
One idea is to move the website docs into the wiki repo, which would make this project a little simpler.
https://github.com/codeselfstudy/codeselfstudy_wiki

**Comment by datadaveshin** [comment]
Which docs are your referring to? The ones in the readme?

**Comment by j127** [comment]
There are some docs in [this directory](https://github.com/codeselfstudy/codeselfstudy/tree/master/docs) that are written with [mdbook](https://rust-lang.github.io/mdBook/). There is a separate mdbook for the new wiki over [here](https://github.com/codeselfstudy/codeselfstudy_wiki) though, so I'm wondering if they should be merged into the wiki or kept separate.

**Comment by j127** [comment]
I moved the docs into the other wiki repo today (at wiki.codeselfstudy.com if it deploys without breaking). I think we could move the wiki into this dockerized repo on the top-level domain later, but it would slow things down to do it now.
