### ISSUE TITLE
Ignore CSS for Github language classification

### ISSUE THREAD

**Issue by datadaveshin** [codeselfstudy/codeselfstudy#54]
Currently, Github is listing this site as using CSS as the language - people with less experience could pin the repo on their profiles, but it would be better if the language detected was JavaScript (or anything besides HTML/CSS.

![code-self-study-classification](https://user-images.githubusercontent.com/14435667/78820129-26b50000-798c-11ea-9c61-ca8fbd32f30d.png)

Tips from:
[github community](https://github.community/t5/How-to-use-Git-and-GitHub/how-to-change-the-category/td-p/27790)
[hackernoon](https://hackernoon.com/how-to-change-repo-language-in-github-c3e07819c5bb)

**Comment by datadaveshin** [comment]
Josh - ok for you? Ignore CSS?

**Comment by j127** [comment]
Sounds good to me. I wonder why it detects so much CSS.

**Comment by j127** [comment]
I wonder if the JSX files with the file extension `.js` throw it off.

**Comment by datadaveshin** [comment]
Yeah, I don't know... now I can't remember if I cloned or forked the site, lol

Anyway, it's driving me crazy, if no one volunteers by the next time I'm ready to contribute to open source - like tonight, I'll do it, lol

**Comment by j127** [comment]
Either way works. I think you have access to push. If you push changes to a new branch, you could make a pull request that way.

**Comment by datadaveshin** [comment]
Ok, fixing this, apparently, vendor files, etc. count also, that's likely where the CSS is coming in from. 

I found if you click the colored bar in the code part, you can see how it's divided up!

![Screen Shot 2020-04-09 at 1 25 06 PM](https://user-images.githubusercontent.com/14435667/78937729-d5793f00-7a65-11ea-8f1d-cc17ce98807b.png)

**Comment by j127** [comment]
I just saw your comment after I posted my other comment. That's strange. I hope the new file fixes it. If not, we could temporarily remove the dependencies, wait for the update, and then add them back after the `.gitattributes` file is picked up.
